# ARRAYS

In [6]:
import numpy as np
y = np.array([1,2,3,4,5])
print(y)

[1 2 3 4 5]


# # Check weather it is array or not

In [8]:
print(type(y))

<class 'numpy.ndarray'>


# # another way

In [9]:
y

array([1, 2, 3, 4, 5])

## Taking input

In [12]:
l = []
for i in range(1,5):
    n = int(input(f"Enter element {i}: "))
    l.append(n)
    
l = np.array(l)
print(l)

Enter element 1: 11
Enter element 2: 22
Enter element 3: 33
Enter element 4: 44
[11 22 33 44]


# Creating n dimentional arrays

In [22]:
# 1 dimentional
ar1 = np.array([1,2,3])
print(ar1.ndim)
print(ar1)

1
[1 2 3]


In [23]:
# 2 dimentional
ar2 = np.array([[1,2,3]])
print(ar2.ndim)
print(ar2)

2
[[1 2 3]]


In [24]:
# 3 dimentional
ar3 = np.array([[[1,2,3]]])
print(ar3.ndim)
print(ar3)

3
[[[1 2 3]]]


In [27]:
# Assigning dimention
arrn = np.array([1,2,3,4],ndmin = 32)
print(arrn.ndim)
print(arrn)

32
[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[1 2 3 4]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]
