# Zeros

In [6]:
import numpy as np
ar_zero = np.zeros(4)
print(ar_zero)
print("\n")

#multi dimenion
ar_zero = np.zeros((3,5))
print(ar_zero)

[0. 0. 0. 0.]


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


# Ones

In [7]:
ar_ones = np.ones(5)
print(ar_ones)

[1. 1. 1. 1. 1.]


# Empty

In [8]:
ar_empty = np.empty(5)
print(ar_empty) #will fill with previous one

[1. 1. 1. 1. 1.]


# Range

In [12]:
ar_range = np.arange(0,10,2)
print(ar_range) #print elements in a range

[0 2 4 6 8]


# Diagonal

In [16]:
ar_diagonal = np.eye(5,5)
print(ar_diagonal) #will print a diagonal

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


# Linespace

In [26]:
ar_line = np.linspace(0,20,num=5)
print(ar_line)

[ 0.  5. 10. 15. 20.]
