# rand()

In [2]:
import numpy as np
a = np.random.rand(5)
print(a)

[0.94355346 0.3602441  0.00864277 0.66167261 0.8628378 ]


# randn()

In [3]:
b = np.random.randn(5)
print(b)

[ 0.4535686  -1.1446815   1.40530404 -0.93569386 -1.75197961]


# ranf()

In [4]:
c = np.random.ranf(5)
print(c)

[0.5613428  0.11595523 0.38221178 0.53792677 0.24073786]


# randint()

In [8]:
d = np.random.randint(5,100,(5,3))
print(d)

[[79 19 14]
 [30 61 94]
 [54 91  5]
 [57 11 77]
 [76  5 48]]
