# ARITHMATIC OPERATORS

In [1]:
import numpy as np
a = np.array([1,2,3,4])
b = np.array([1,2,3,4])

## Addition

In [2]:
print(a+b)

[2 4 6 8]


In [3]:
print(np.add(a,b))

[2 4 6 8]


## Subtract 

In [4]:
print(a-b)

[0 0 0 0]


In [5]:
print(np.subtract(a,b))

[0 0 0 0]


## Multiply

In [6]:
print(a*b)

[ 1  4  9 16]


In [7]:
print(np.multiply(a,b))

[ 1  4  9 16]


## Divide

In [8]:
print(a/b)

[1. 1. 1. 1.]


In [9]:
print(np.divide(a,b))

[1. 1. 1. 1.]


## Remainder

In [10]:
print(a%b)

[0 0 0 0]


In [11]:
print(np.mod(a,b))

[0 0 0 0]


## Power

In [12]:
print(a**b)

[  1   4  27 256]


In [13]:
print(np.power(a,b))

[  1   4  27 256]


## Reciprocal

In [24]:
print(1/a)

[1.         0.5        0.33333333 0.25      ]


In [25]:
print(np.reciprocal(a))

[1 0 0 0]
