# ARITHMATIC FUNCTIONS

In [28]:
import numpy as np

a = np.array([1,2,3,4,5])

## MINIMUM

In [29]:
print(a.min())

1


## Maximum

In [30]:
print(a.max())

5


## Minimum location

In [31]:
print(a.argmin())

0


## Maximum Location

In [32]:
print(a.argmax())

4


## In 2D array

In [33]:
b = np.array([[1,2,3,4],[5,6,7,8]])
print(b.max(1)) # 1 = columns
print(b.max(0)) # 0 = rows

[4 8]
[5 6 7 8]


## Square root

In [34]:
print(np.sqrt(a))

[1.         1.41421356 1.73205081 2.         2.23606798]


## Sin

In [36]:
print(np.sin(a))

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


## Cos

In [37]:
print(np.cos(a))

[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219]


## Cumsum

In [38]:
print(a.cumsum())

[ 1  3  6 10 15]
