# Shape

In [1]:
import numpy as np
a = np.array([[1,2,3],[1,2,3]])
print(a)
print(a.shape)

[[1 2 3]
 [1 2 3]]
(2, 3)


In [5]:
b = np.array([1,2,3,4], ndmin=10)
print(b)
print(b.shape)
print(b.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
(1, 1, 1, 1, 1, 1, 1, 1, 1, 4)
10


# Reshape

In [7]:
a = a.reshape(6,1)
print(a)

[[1]
 [2]
 [3]
 [1]
 [2]
 [3]]


In [16]:
d = np.array([[1,2,3,4],[5,6,7,8]])
d = d.reshape(2,2,2)
print(d)
print(d.shape)
print(d.ndim)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)
3


In [23]:
d = d.reshape(-1)
print(d)
print(d.shape)
print(d.ndim)

[1 2 3 4 5 6 7 8]
(8,)
1
