# Broadcasting

## Eltement must be in same dimention

In [13]:
import numpy as np
a = np.array([1,2,3,4])
print(a.shape)
b = np.array([1,2,3])
print(b.shape)
print(a+b)

(4,)
(3,)


ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [20]:
a = np.array([1,2,3,4])
print(a.shape)
b = np.array([1,2,3,4])
print(b.shape)
print(a+b)

(4,)
(4,)
[2 4 6 8]


## OR elements either of them each diemnsion must contain 1

In [17]:
a = np.array([1,2,3,4])
print(a.shape)
b = np.array([[1,2],[2,3],[3,4]])
print(b.shape)
print(a+b)

(4,)
(3, 2)


ValueError: operands could not be broadcast together with shapes (4,) (3,2) 

In [18]:
a = np.array([1,2,3,4])
print(a.shape)
b = np.array([[1],[2],[3]])
print(b.shape)
print(a+b)

(4,)
(3, 1)
[[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]]
