# Joining

In [1]:
import numpy as np

## Concatenate

In [22]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
c = np.concatenate((a,b))
print(c)

[1 2 3 4 5 6 7 8]


In [23]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
c = np.concatenate((a,b),axis=1)
print(c)

[[1 2 5 6]
 [3 4 7 8]]


In [24]:
a = np.array([
    [
        [1,2],[3,4]
        
    ],
    [
        [5,6],[6,7]
    ]
])
b = np.array([
    [
        [11,12],[13,14]
        
    ],
    [
        [15,16],[16,17]
    ]
])
c = np.concatenate((a,b))
print(c)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 6  7]]

 [[11 12]
  [13 14]]

 [[15 16]
  [16 17]]]


## Stack

In [25]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
c = np.stack((a,b))
print(c)

[[1 2 3 4]
 [5 6 7 8]]


In [26]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
c = np.stack((a,b))
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [27]:
a = np.array([
    [
        [1,2],[3,4]
        
    ],
    [
        [5,6],[6,7]
    ]
])
b = np.array([
    [
        [11,12],[13,14]
        
    ],
    [
        [15,16],[16,17]
    ]
])
c = np.stack((a,b))
print(c)

[[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 6  7]]]


 [[[11 12]
   [13 14]]

  [[15 16]
   [16 17]]]]


In [30]:
a = 5
b = 6
c = np.stack((a,b))
print(c)

[5 6]
