# Search

In [1]:
import numpy as np

In [4]:
a = np.array([1,2,3,4,5,6,7,8,9,2,53,2,64,2])
print(np.where(a==2))
print(np.where((a%2)==0))

(array([ 1,  9, 11, 13], dtype=int64),)
(array([ 1,  3,  5,  7,  9, 11, 12, 13], dtype=int64),)


# SearchSorted

In [16]:
b = np.array([10,20,30,50,60,70,80])
print(np.searchsorted(b,77))

6


# Sort

In [21]:
c = np.random.randint(1,100,10)
print(c)
print(np.sort(c))

[ 8 34 34 76 97 38 39 94 39 31]
[ 8 31 34 34 38 39 39 76 94 97]


In [32]:
d = np.array(["madara", "itachi", "obito", "sasuke", "shisui", "sarada"])
print(np.sort(d))

['itachi' 'madara' 'obito' 'sarada' 'sasuke' 'shisui']


# Filter Array

In [33]:
e = np.array(["madara", "itachi", "obito", "sasuke", "shisui", "sarada"])
f = np.array([False,True,False,True,False,True])
print(e[f])

['itachi' 'sasuke' 'sarada']
