In [1]:
import numpy as np

# Shuffle

In [4]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
print(a)
np.random.shuffle(a)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]
[ 8  7  5  1  3  2  9  6  4 10]


# Uniique

In [5]:
b = np.array([1,2,1,2,3,53,2,42,3,4,23,2,1,3])
print(np.unique(b))

[ 1  2  3  4 23 42 53]


# Resize

In [6]:
c = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(np.resize(c,(4,3)))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
