# Insert

In [1]:
import numpy as np

In [3]:
a = np.array([1,2,3,4,5])
print(a)
a = np.insert(a,3,69)
print(a)

[1 2 3 4 5]
[ 1  2  3 69  4  5]


In [7]:
b = np.array([
    [1,2,3],
    [4,5,6]
])
c = np.insert(b,2,[7,8,9],axis=0)
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


# Delete

In [10]:
x = np.array([1,2,3,4,5,6])
print(x)
xd = np.delete(x,-4)
print(xd)

[1 2 3 4 5 6]
[1 2 4 5 6]
