# Matrix

In [1]:
import numpy as np

In [12]:
m = np.matrix([[1,2],[3,4]])
n = np.matrix([[1,2],[3,4]])
print(m)
print(n)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]


In [8]:
print(m+n)

[[2 4]
 [6 8]]


In [10]:
print(m-n)

[[0 0]
 [0 0]]


In [11]:
print(m*n)

[[ 7 10]
 [15 22]]


In [14]:
print(np.dot(m,n))

[[ 7 10]
 [15 22]]
