# Marix Functions

In [1]:
import numpy as np


## Transpose

In [3]:
m = np.matrix([
    [1,2,3,4],
    [5,6,7,8]
])

In [6]:
n = m.transpose()
print(n)

[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [7]:
o = n.transpose()
print(o)

[[1 2 3 4]
 [5 6 7 8]]


## Swap Axis

In [13]:
m = np.matrix([[1,2],[3,4]])
print(m)
print()
print(m.swapaxes(0,1))

[[1 2]
 [3 4]]

[[1 3]
 [2 4]]


## Inverse

In [14]:
print(np.linalg.inv(m))

[[-2.   1. ]
 [ 1.5 -0.5]]


## Power

In [16]:
print(np.linalg.matrix_power(m,3))

[[ 37  54]
 [ 81 118]]
